# Permalinks
permalink:           pretty

# Setup
title:               Kevin Susilo
tagline:             Data Science Blog
url:                 https://github.com/kevinsusilo/kevinsusilo.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Kevin Susilo
  url:               
  email:             

# Custom vars
version:             2.0.0
github:
  repo:             

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
